name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - '26.2.3'
        rebar3:
          - '3.22.1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Erlang/OTP
        uses: erlef/setup-beam@v1.17.5
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
      - name: run concuerror tests
        run: make concuerror_tests
